version: 0.0
os: windows
files:
 - source: C:\docker_demo\AWS Demo\demo-app\scripts
   destination: C:\nginx\html
hooks:
 BeforeInstall:
   - location: scripts\install_nginx.ps1
     timeout: 300
 AfterInstall:
   - location: scripts\start_nginx.ps1
     timeout: 300