version: 0.0
os: windows
files:
 - source: /
   destination: C:\inetpub\wwwroot
hooks:
 BeforeInstall:
   - location: scripts\install_iis.ps1
     timeout: 300
     runas: Administrator
 AfterInstall:
   - location: scripts\copy_files.ps1
     timeout: 300
     runas: Administrator
 ApplicationStart:
   - location: scripts\start_iis.ps1
     timeout: 300
     runas: Administrator