version: 0.2
phases:
 install:
   commands:
     - echo Installing phase - no dependencies for static website
 pre_build:
   commands:
     - echo Pre-Build phase - nothing to do
 build:
   commands:
     - echo Build phase - no build steps needed for static HTML
 post_build:
   commands:
     - echo Post-Build phase - build completed successfully
artifacts:
 files:
   - '**/*'
