version: 0.2

phases:

  install:

    commands:

      - echo "Downloading and installing Nginx for Windows"

      - powershell Invoke-WebRequest -Uri "https://nginx.org/download/nginx-1.24.0.zip" -OutFile "nginx.zip"

      - powershell Expand-Archive nginx.zip -DestinationPath C:\nginx

      - powershell Start-Process -FilePath "C:\nginx\nginx.exe"

  build:

    commands:

      - echo "Build started on $(Get-Date)"

      - Copy-Item index.html -Destination "C:\nginx\html\"

  post_build:

    commands:

      - echo "Restarting Nginx"

      - powershell Stop-Process -Name nginx -Force

      - powershell Start-Process -FilePath "C:\nginx\nginx.exe"

artifacts:

  files:

    - index.html 