version: 0.2
phases:
 install:
   commands:
     - echo Installing Chocolatey...
     - Set-ExecutionPolicy Bypass -Scope Process -Force
     - [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
     - iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
     - choco --version
 pre_build:
   commands:
    - echo Installing nginx using Chocolatey
    - choco install nginx -y --force
 build:
   commands:
     - echo Build phase started.
 post_build:
   commands:
     - echo Build completed successfully.
artifacts:
 files:
   - '**/*'