version: 0.2

phases:

  install:

    commands:

      - echo "Setting execution policy..."

      - powershell -Command "Set-ExecutionPolicy Bypass -Scope Process -Force"

      - echo "Checking if Chocolatey is installed..."

      - if exist "C:\ProgramData\chocolatey\bin\choco.exe" (

            echo "Chocolatey already installed."

        ) else (

            echo "Installing Chocolatey..."

            powershell -Command "[System.Net.ServicePointManager]::SecurityProtocol = 'Tls12'; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))"

        )

      - echo "Refreshing environment..."

      - refreshenv || echo "refreshenv command not found"

      - echo "Verifying Chocolatey installation..."

      - choco -v

  build:

    commands:

      - echo "Installing Nginx..."

      - choco install nginx -y --force

      - echo "Nginx installation completed."

artifacts:

  files:

    - index.html 