version: 0.2

phases:

  install:

    commands:

      - echo "Installing Chocolatey Package Manager..."

      - setx PATH "%PATH%;C:\ProgramData\chocolatey\bin"

      - powershell -Command "Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))"

      - refreshenv

      - echo "Installing Nginx using Chocolatey..."

      - choco install nginx -y

      - echo "Nginx installation completed."

  build:

    commands:

      - echo "Starting Nginx..."

      - powershell Start-Process -FilePath "C:\tools\nginx\nginx.exe" -NoNewWindow -PassThru

      - sleep 5

      - powershell Get-Process nginx

  post_build:

    commands:

      - echo "Allowing traffic on port 80 for Nginx..."

      - netsh advfirewall firewall add rule name="Allow Nginx" dir=in action=allow protocol=TCP localport=80

artifacts:

  files:

    - index.html 