version: 0.2
phases:
 install:
   commands:
     - echo "Installing IIS (Windows Web Server)"
     - powershell Install-WindowsFeature -name Web-Server -IncludeManagementTools
 build:
   commands:
     - echo "Build started on $(Get-Date)"
     - Copy-Item index.html -Destination "C:\inetpub\wwwroot\"
 post_build:
   commands:
     - echo "Configuring IIS"
     - powershell Restart-Service W3SVC
artifacts:
 files:
   - appspec.yml
   - scripts/**/*
   - "*.html"
   #- '**/*'
 base-directory: . 
