version: 0.2

phases:

  install:

    commands:

      - echo "Installing Chocolatey..."

      - powershell -Command "Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))"

      - echo "Adding Chocolatey to PATH..."

      - set "PATH=%PATH%;C:\ProgramData\chocolatey\bin"

      - echo "Installing Nginx..."

      - choco install nginx -y

      - echo "Nginx installation completed."

  pre_build:

    commands:

      - echo "Verifying Nginx installation..."

      - if exist "C:\tools\nginx\nginx.exe" (echo "Nginx installed successfully.") else (echo "Nginx installation failed!" && exit 1)

  build:

    commands:

      - echo "Starting Nginx..."

      - Start-Process -FilePath "C:\tools\nginx\nginx.exe" -NoNewWindow

      - echo "Waiting for Nginx to start..."

      - Start-Sleep -s 5

      - echo "Checking running processes..."

      - Get-Process nginx

  post_build:

    commands:

      - echo "Configuring firewall rule for Nginx..."

      - powershell -Command "New-NetFirewallRule -DisplayName 'Allow Nginx' -Direction Inbound -Protocol TCP -LocalPort 80 -Action Allow"

      - echo "Firewall rule added."

artifacts:

  files:

    - index.html 