version: 0.2

phases:

  install:

    commands:

      - echo "Downloading and installing Nginx for Windows"

      - powershell Invoke-WebRequest -Uri "https://nginx.org/download/nginx-1.24.0.zip" -OutFile "C:\nginx.zip"

      - powershell Expand-Archive -Path "C:\nginx.zip" -DestinationPath "C:\"

  build:

    commands:

      - echo "Starting Nginx"

      - powershell Start-Process -FilePath "C:\nginx\nginx.exe" -NoNewWindow -Wait

  post_build:

    commands:

      - echo "Allowing Nginx in firewall"

      - powershell New-NetFirewallRule -DisplayName "Allow Nginx" -Direction Inbound -Protocol TCP -LocalPort 80 -Action Allow

artifacts:

  files:

    - index.html 